---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: sweetrpg-auth-web
  labels:
    release: prometheus

spec:
  podMetricsEndpoints:
    - port: http
  selector:
    matchLabels:
        app.kubernetes.io/name: auth-web
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: auth
  namespaceSelector:
    matchNames:
      - sweetrpg-auth
