---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-redis
  labels:
    app: auth-redis

spec:
  selector:
    matchLabels:
      app: auth-redis
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-redis
        version: v1
    spec:
      serviceAccountName: auth-redis
      containers:
        - name: auth-redis
          image: redis:7-alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "20m"
              memory: "55Mi"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
